# Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import File

In [ ]:
df = pd.read_csv("sales_dataset.csv")

In [ ]:
df

                                                                                                                                          VQ  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   B09NQ4DD29
                                                                                       J0285   J0285-SKD-XS    Set           XS   B08QGN4RYQ
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   B09SDXG1CP
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  B09K3Z6TT3
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    B09CTCDDQ4
...                                                                                                                                      ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL   B098112V2V
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M    B09VC6KHX8
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL  B0982YZ51B
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS   B0894Y2NJQ
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S    B0894X27FC

                                                                                                                                    Shipped  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   Unshipped
                                                                                       J0285   J0285-SKD-XS    Set           XS   Unshipped
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL     Shipped
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL    Shipped
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M      Shipped
...                                                                                                                                     ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL     Shipped
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M      Shipped
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL    Shipped
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS     Shipped
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S      Shipped

                                                                                                                                  1  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   1
                                                                                       J0285   J0285-SKD-XS    Set           XS   1
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   1
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  1
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    1
...                                                                                                                              ..
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL   1
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M    1
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL  1
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS   1
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S    1

                                                                                                                                  INR  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   INR
                                                                                       J0285   J0285-SKD-XS    Set           XS   INR
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   INR
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  INR
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    INR
...                                                                                                                               ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL   INR
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M    INR
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL  INR
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS   INR
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S    INR

                                                                                                                                     382  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS    635.0
                                                                                       J0285   J0285-SKD-XS    Set           XS   1523.0
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL    771.0
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL   345.0
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    1099.0
...                                                                                                                                  ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL    517.0
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M     999.0
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL   690.0
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS   1199.0
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S     696.0

                                                                                                                                    CHENNAI  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS     LUCKNOW
                                                                                       J0285   J0285-SKD-XS    Set           XS     LUCKNOW
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL     CHENNAI
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL    LUCKNOW
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M      KOLKATA
...                                                                                                                                     ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL   HYDERABAD
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M     GURUGRAM
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL  HYDERABAD
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS       Halol
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S       Raipur

                                                                                                                                     TAMIL NADU  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   UTTAR PRADESH
                                                                                       J0285   J0285-SKD-XS    Set           XS   UTTAR PRADESH
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL      TAMIL NADU
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  UTTAR PRADESH
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M      WEST BENGAL
...                                                                                                                                         ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL       TELANGANA
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M          HARYANA
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL      TELANGANA
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS         Gujarat
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S     CHHATTISGARH

                                                                                                                                    600005  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   226024.0
                                                                                       J0285   J0285-SKD-XS    Set           XS   226024.0
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   600011.0
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  226010.0
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    700086.0
...                                                                                                                                    ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL   500013.0
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M    122004.0
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL  500049.0
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS   389350.0
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S    492014.0

                                                                                                                                  IN  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   IN
                                                                                       J0285   J0285-SKD-XS    Set           XS   IN
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   IN
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  IN
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    IN
...                                                                                                                               ..
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL   IN
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M    IN
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL  IN
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS   IN
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S    IN

                                                                                                                                                                         Unnamed: 9  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS                                                 NaN
                                                                                       J0285   J0285-SKD-XS    Set           XS                                                 NaN
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   Amazon PLCC Free-Financing Universal Merchant ...
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  Amazon PLCC Free-Financing Universal Merchant ...
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M         IN Core Free Shipping 2015/04/08 23-48-5-108
...                                                                                                                                                                             ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL                                                 NaN
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M         IN Core Free Shipping 2015/04/08 23-48-5-108
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL                                                NaN
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS        IN Core Free Shipping 2015/04/08 23-48-5-108
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S         IN Core Free Shipping 2015/04/08 23-48-5-108

                                                                                                                                  FALSE  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   False
                                                                                       J0285   J0285-SKD-XS    Set           XS   False
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   False
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  False
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    False
...                                                                                                                                 ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL   False
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M    False
407-9547469-3152358 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0157   J0157-DR-XXL    Western Dress XXL  False
402-6184140-0545956 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0012   J0012-SKD-XS    Set           XS   False
408-7436540-8728312 05-31-22 Shipped                      Amazon   Amazon.in Expedited J0003   J0003-SET-S     Set           S    False

                                                                                                                                 Unnamed: 11  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS          NaN
                                                                                       J0285   J0285-SKD-XS    Set           XS          NaN
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL    Easy Ship
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL   Easy Ship
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M           NaN
...                                                                                                                                      ...
406-6001380-7673107 05-31-22 Shipped                      Amazon   Amazon.in Expedited JNE3697 JNE3697-KR-XL   kurta         XL          NaN
402-9551604-7544318 05-31-22 Cancelled                    Amazon   Amazon.in Expedited SET401  SET401-KR-NP-M  Set           M           NaN

In [ ]:
df.head()

                                                                                                                                          VQ  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   B09NQ4DD29
                                                                                       J0285   J0285-SKD-XS    Set           XS   B08QGN4RYQ
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   B09SDXG1CP
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  B09K3Z6TT3
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    B09CTCDDQ4

                                                                                                                                    Shipped  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   Unshipped
                                                                                       J0285   J0285-SKD-XS    Set           XS   Unshipped
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL     Shipped
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL    Shipped
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M      Shipped

                                                                                                                                  1  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   1
                                                                                       J0285   J0285-SKD-XS    Set           XS   1
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   1
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  1
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    1

                                                                                                                                  INR  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   INR
                                                                                       J0285   J0285-SKD-XS    Set           XS   INR
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   INR
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  INR
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    INR

                                                                                                                                     382  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS    635.0
                                                                                       J0285   J0285-SKD-XS    Set           XS   1523.0
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL    771.0
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL   345.0
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    1099.0

                                                                                                                                  CHENNAI  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   LUCKNOW
                                                                                       J0285   J0285-SKD-XS    Set           XS   LUCKNOW
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   CHENNAI
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  LUCKNOW
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    KOLKATA

                                                                                                                                     TAMIL NADU  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   UTTAR PRADESH
                                                                                       J0285   J0285-SKD-XS    Set           XS   UTTAR PRADESH
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL      TAMIL NADU
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  UTTAR PRADESH
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M      WEST BENGAL

                                                                                                                                    600005  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   226024.0
                                                                                       J0285   J0285-SKD-XS    Set           XS   226024.0
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   600011.0
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  226010.0
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    700086.0

                                                                                                                                  IN  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   IN
                                                                                       J0285   J0285-SKD-XS    Set           XS   IN
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   IN
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  IN
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    IN

                                                                                                                                                                         Unnamed: 9  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS                                                 NaN
                                                                                       J0285   J0285-SKD-XS    Set           XS                                                 NaN
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   Amazon PLCC Free-Financing Universal Merchant ...
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  Amazon PLCC Free-Financing Universal Merchant ...
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M         IN Core Free Shipping 2015/04/08 23-48-5-108

                                                                                                                                  FALSE  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS   False
                                                                                       J0285   J0285-SKD-XS    Set           XS   False
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL   False
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL  False
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M    False

                                                                                                                                 Unnamed: 11  \
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS          NaN
                                                                                       J0285   J0285-SKD-XS    Set           XS          NaN
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL    Easy Ship
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL   Easy Ship
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M           NaN

                                                                                                                                  FALSE.1
403-8475170-7369939 05-17-22 Cancelled                    Amazon   Amazon.in Expedited SET324  SET324-KR-NP-XS Set           XS     False
                                                                                       J0285   J0285-SKD-XS    Set           XS     False
406-1213087-3642728 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3798 JNE3798-KR-XL   Western Dress XL     False
171-9475828-2365944 05-17-22 Shipped - Delivered to Buyer Merchant Amazon.in Standard  JNE3752 JNE3752-KR-XXXL kurta         3XL    False
171-3721797-1783547 05-17-22 Shipped                      Amazon   Amazon.in Expedited SET282  SET282-KR-PP-M  Set           M      False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62522 entries, ('403-8475170-7369939', '05-17-22', 'Cancelled', 'Amazon', 'Amazon.in', 'Expedited', 'SET324', 'SET324-KR-NP-XS', 'Set', 'XS') to ('408-7436540-8728312', '05-31-22', 'Shipped', 'Amazon', 'Amazon.in', 'Expedited', 'J0003', 'J0003-SET-S', 'Set', 'S')
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   VQ           62522 non-null  object
 1   Shipped      59309 non-null  object
 2   1            62522 non-null  int64
 3   INR          58731 non-null  object
 4   382          58731 non-null  float64
 5   CHENNAI      62504 non-null  object
 6   TAMIL NADU   62504 non-null  object
 7   600005       62504 non-null  float64
 8   IN           62504 non-null  object
 9   Unnamed: 9   38235 non-null  object
 10  FALSE        62522 non-null  bool
 11  Unnamed: 11  18324 non-null  object
 12  FALSE.1      62522 non-null  bool
dtypes: bool(2), float64(2), int64(1), object(8)
memory usage: 8.9+ MB

In [ ]:
df.isnull().sum()

VQ                 0
Shipped         3213
1                  0
INR             3791
382             3791
CHENNAI           18
TAMIL NADU        18
600005            18
IN                18
Unnamed: 9     24287
FALSE              0
Unnamed: 11    44198
FALSE.1            0
dtype: int64

# Data Cleaning

In [ ]:
#Fill NaN values with median of Amount(Amount=0)
df.loc[df['Status'].str.contains('Cancelled', case=False), 'Amount'] = 0
median_amount = df['Amount'].median()
df['Amount'] = df['Amount'].fillna(median_amount)

KeyError: 'Status'

In [ ]:
df.isnull().sum()

In [ ]:
#Convert Date Column
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [ ]:
# Amount & currency missing
df['currency'] = df['currency'].fillna(df['currency'].mode()[0])

# Courier Status
df['Courier Status'] = df['Courier Status'].fillna('Not Available')

# Promotion IDs
df['promotion-ids'] = df['promotion-ids'].fillna('No Promotion')

# Fulfilled By
df['fulfilled-by'] = df['fulfilled-by'].fillna('Unknown')

df['ship-postal-code'] = df['ship-postal-code'].fillna(df['ship-postal-code'].mode()[0])
df['B2B'] = df['B2B'].fillna(False)

# Shipping details (small missing count)
df[['ship-city','ship-state','ship-country']] = df[['ship-city','ship-state','ship-country']].fillna('Unknown')

In [ ]:
df.isnull().sum()

In [ ]:
# Find all exact duplicates
duplicates = df[df.duplicated()]
print(duplicates)

In [ ]:
# Check if any Order IDs are repeated
order_duplicates = df[df.duplicated(subset=['Order ID'])]
print(order_duplicates)

In [ ]:
num_duplicates = df.duplicated().sum()
print("Number of duplicate rows:", num_duplicates)

In [ ]:
df = df.drop_duplicates()

In [ ]:
num_duplicates = df.duplicated().sum()
print("Number of duplicate rows:", num_duplicates)

# **FINANCIAL PERFORMANCE ANALYSIS**

## 1) Analyzing total revenue growth over time

In [ ]:
#Total Revenue Growth Over Time
total_revenue = df['Amount'].sum()
print("Total Revenue:", round(total_revenue, 2))

In [ ]:
#Monthly Sales Breakdown
monthly_sales = (
    df.groupby(df['Date'].dt.to_period('M'))['Amount']
    .sum()
    .reset_index()
)

monthly_sales['Date'] = monthly_sales['Date'].astype(str)
monthly_sales

In [ ]:
#Monthly Revenue Trend (Growth Over Time)
monthly_revenue = df.groupby(df['Date'].dt.to_period('M'))['Amount'].sum()

plt.figure(figsize=(10,5))
monthly_revenue.plot()
plt.plot(monthly_revenue.index, monthly_revenue.values, marker='o',color='b')
plt.title("Monthly Revenue Growth Over Time")
plt.xlabel("Month")
plt.ylabel("Total Revenue")
plt.grid(True)
plt.show()

In [ ]:
#Monthly Sales Count
monthly_order_count = (
    df.groupby(df['Date'].dt.to_period('M'))['Order ID']
    .count()
    .reset_index(name='Total Orders')
)

monthly_order_count['Date'] = monthly_order_count['Date'].astype(str)
monthly_order_count

In [ ]:
#Weekly Sales
weekday_sales = (
    df.groupby(df['Date'].dt.day_name())['Amount']
    .sum()
    .reset_index()
)
weekday_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
weekday_sales['Date'] = pd.Categorical(
    weekday_sales['Date'],
    categories=weekday_order,
    ordered=True
)

weekday_sales = weekday_sales.sort_values('Date')
weekday_sales

In [ ]:
weekday_sales = (
    df.groupby(df['Date'].dt.day_name())['Amount']
    .sum()
    .reindex(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])
)

In [ ]:
plt.figure(figsize=(8,5))
plt.plot(weekday_sales.index, weekday_sales.values, marker='o',color='b')
plt.title("Weekly Sales Trend (Day-wise)")
plt.xlabel("Day of the Week")
plt.ylabel("Total Sales Amount")
plt.grid(True)
plt.show()

## 2) Identifying best-selling products and seasonal sales trends

In [ ]:
#Best-Selling Products (By Quantity)
top_products_qty = df.groupby('SKU')['Qty'].sum().sort_values(ascending=False).head(10)
top_products_qty

In [ ]:
#Best-Selling Products (By Revenue)
top_products_revenue = df.groupby('SKU')['Amount'].sum().sort_values(ascending=False).head(10)
top_products_revenue

## 3) Calculating the average order value to understand spending behavior

In [ ]:
# Total revenue
total_revenue = df['Amount'].sum()

# Total orders
total_orders = len(df)

# AOV
AOV = total_revenue / total_orders

print("AOV:", round(AOV, 2))

In [ ]:
#Average Order Value Trend Over Time
monthly_aov = (
    df
    .groupby(df['Date'].dt.to_period('M'))
    .apply(lambda x: x['Amount'].sum() / len(x))
)

plt.figure(figsize=(10,5))
monthly_aov.plot(marker='o', color='b')
plt.title("Average Order Value Trend Over Time")
plt.xlabel("Month")
plt.ylabel("AOV")
plt.grid(True)
plt.show()

# **CUSTOMER INSIGHTS ANALYSIS**

## 1) Identifying top-performing locations based on sales volume

In [ ]:
#Top States by Revenue
state_sales = df.groupby('ship-state')['Amount'].sum().sort_values(ascending=False)
state_sales.head(10)

In [ ]:
#Top Cities by Revenue
city_sales = df.groupby('ship-city')['Amount'].sum().sort_values(ascending=False)
city_sales.head(10)

In [ ]:
#Visualization – Top 10 States
plt.figure(figsize=(10,5))
state_sales.head(10).plot(kind='bar')
plt.title("Top 10 States by Sales Revenue")
plt.xlabel("State")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.show()

## 2) Analyzing order cancellation trends and customer retention

In [ ]:
cancel_keywords = [
    'cancelled',
    'damaged',
    'lost in transit',
    'rejected by buyer',
    'returned to seller',
    'returning to seller'
]

total_cancelled_orders = df['Status'].str.lower().str.contains(
    '|'.join(cancel_keywords),
    na=False
).sum()

print("Total Cancelled Orders:", total_cancelled_orders)

In [ ]:
total_orders = len(df)
print("Total Orders:", total_orders)

In [ ]:
#Overall Cancellation Rate
overall_cancellation_rate = (total_cancelled_orders / total_orders) * 100
print("Overall Cancellation Rate:", round(overall_cancellation_rate, 2), "%")

In [ ]:
#Monthly Cancellation Rate
df['Month'] = df['Date'].dt.to_period('M')

monthly_cancellation = (
    df.groupby('Month')
      .apply(lambda x:
             x['Status'].str.lower().str.contains(
                 '|'.join(cancel_keywords), na=False
             ).sum() / len(df) * 100
            )
      .round(2)
)
monthly_cancellation

In [ ]:
#Monthly Cancellation Trend
plt.figure(figsize=(10,5))
monthly_cancellation.plot(marker='o', color='red')
plt.title("Month-wise Cancellation Rate (%)")
plt.xlabel("Month")
plt.ylabel("Cancellation Rate (%)")
plt.grid(True)
plt.show()

In [ ]:
#Customer Retention (Repeat Orders)
repeat_customers = df['Order ID'].value_counts()
retained_orders = repeat_customers[repeat_customers > 1].count()

print("Repeat Orders Count:", retained_orders)

## 3) Differentiating B2B vs. B2C customer behavior for targeted marketing

In [ ]:
#Order Volume Comparison
b2b_b2c_orders = df['B2B'].value_counts()

plt.figure()
b2b_b2c_orders.plot(kind='bar')
plt.title("B2B vs B2C Order Volume")
plt.xlabel("Customer Type (B2B)")
plt.ylabel("Number of Orders")
plt.xticks(rotation=0)
plt.show()

In [ ]:
#Revenue Comparison
b2b_b2c_revenue = df.groupby('B2B')['Amount'].sum()
b2b_b2c_revenue

In [ ]:
#Average Order Value by Customer Type
aov_by_customer_type = (
    df
    .groupby('B2B')
    .apply(lambda x: x['Amount'].sum() / len(x))
    .round(2)
)

aov_by_customer_type = aov_by_customer_type.rename("AOV")

aov_by_customer_type

# **LOGISTICS & FULFILLMENT OPTIMIZATION**

## 1) Addressing shipping delays by calculating average shipping times

In [ ]:
#Order Status Distribution
status_dist = df['Status'].value_counts()

plt.figure(figsize=(10,5))
status_dist.plot(kind='bar')
plt.title("Order Status Distribution")
plt.xlabel("Order Status")
plt.ylabel("Number of Orders")
plt.xticks(rotation=90)
plt.show()

In [ ]:
#Courier Status Analysis
courier_status_dist = df['Courier Status'].value_counts()

plt.figure(figsize=(10,5))
courier_status_dist.plot(kind='bar')
plt.title("Courier Status Distribution")
plt.xlabel("Courier Status")
plt.ylabel("Orders")
plt.xticks(rotation=0)
plt.show()

## 2) Comparing orders fulfilled by Amazon vs. Merchant fulfillment

In [ ]:
#Order Volume Comparison
fulfillment_orders = df['Fulfilment'].value_counts()

plt.figure()
fulfillment_orders.plot(kind='bar')
plt.title("Amazon vs Merchant Fulfillment (Order Count)")
plt.xlabel("Fulfilment Type")
plt.ylabel("Orders")
plt.xticks(rotation=0)
plt.show()

In [ ]:
#Revenue Comparison
fulfillment_revenue = df.groupby('Fulfilment')['Amount'].sum()
fulfillment_revenue

In [ ]:
#Cancellation Rate by Fulfilment Type
cancel_by_fulfilment = (
    df[df['Status'].str.lower().str.contains('|'.join(cancel_keywords), na=False)]
    .groupby('Fulfilment')['Order ID']
    .count()
)

# Total orders by Fulfilment type
total_by_fulfilment = (
    df.groupby('Fulfilment')['Order ID']
    .count()
)

# Cancellation Rate (%)
cancel_rate_fulfilment = (
    (cancel_by_fulfilment / total_by_fulfilment) * 100
).round(2)

cancel_rate_fulfilment

## 3) Improving order processing for faster deliveries.

In [ ]:
#Ship Service Level Performance
service_level_orders = df['ship-service-level'].value_counts()

plt.figure()
service_level_orders.plot(kind='bar')
plt.title("Orders by Shipping Service Level")
plt.xlabel("Service Level")
plt.ylabel("Orders")
plt.xticks(rotation=0)
plt.show()

In [ ]:
#Service Level vs Order Status
service_status = pd.crosstab(df['ship-service-level'], df['Status'])
service_status

# **PRODUCT MANAGEMENT & INVENTORY OPTIMIZATION**

## 1) Identifying high-demand product categories

In [ ]:
#Demand by Quantity (True Demand)
category_demand_qty = df.groupby('Category')['Qty'].sum().sort_values(ascending=False)
category_demand_qty.head(10)

In [ ]:
#Demand by Revenue (Business Value)
category_revenue = df.groupby('Category')['Amount'].sum().sort_values(ascending=False)
category_revenue.head(10)

In [ ]:
#Visualization – Top Categories by Quantity
plt.figure(figsize=(10,5))
category_demand_qty.head(10).plot(kind='bar')
plt.title("Top 10 High-Demand Product Categories (by Quantity)")
plt.xlabel("Category")
plt.ylabel("Total Units Sold")
plt.xticks(rotation=45)
plt.show()

## 2) Analyzing the average quantity ordered for efficient stock management.

In [ ]:
#Average Quantity per Order
avg_qty_per_order = df['Qty'].sum() / len(df)

print("Average Quantity per Order:", round(avg_qty_per_order, 2))

In [ ]:
#Average Quantity by Category
avg_qty_by_category = (
    df
    .groupby('Category')
    .apply(lambda x: x['Qty'].sum() / len(df))
    .round(2)
)

avg_qty_by_category = avg_qty_by_category.rename("Avg_Qty_Per_Order")

avg_qty_by_category

In [ ]:
#Chart Visualization for Average Quantity by Category
avg_qty_by_category.plot(kind='line',marker="o", figsize=(10,5),color="b")
plt.title("Average Quantity per Order by Category")
plt.xlabel("Category")
plt.ylabel("Average Quantity per Order")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

## 3) Enhancing inventory control to prevent stockouts or overstocking.

In [ ]:
#Demand Variability by Category
demand_variability = df.groupby('Category')['Qty'].std().sort_values(ascending=False)
demand_variability.head(10)

# **CUSTOMER SATISFACTION & RETURNS ANALYSIS**

## 1) Investigating high return and cancellation rates

In [ ]:
#Order Status Distribution
status_distribution = df['Status'].value_counts()

plt.figure(figsize=(10,5))
status_distribution.plot(kind='bar')
plt.title("Order Status Distribution")
plt.xlabel("Order Status")
plt.ylabel("Number of Orders")
plt.xticks(rotation=90)
plt.show()

## 2) Identifying problematic products/categories to enhance quality

In [ ]:
#Cancellation Rate by Category
cancellation_by_category = (
    df.groupby('Category')
      .apply(lambda x:
             x['Status'].str.lower().str.contains(
                 '|'.join(cancel_keywords), na=False
             ).sum() / len(df) * 100
            )
      .round(2)
)

cancellation_by_category

In [ ]:
#Chat for Cancellation Rate by Category
cancellation_by_category.plot(kind='bar', figsize=(10,5), color='red')
plt.title("Cancellation Rate by Category (%)")
plt.xlabel("Category")
plt.ylabel("Cancellation Rate (%)")
plt.xticks(rotation=45)
plt.show()

In [ ]:
#Cancellation Rate by Shipping Service Level
cancellation_by_service = (
    df.groupby('ship-service-level')
      .apply(lambda x:
             x['Status'].str.lower().str.contains(
                 '|'.join(cancel_keywords), na=False
             ).sum() / len(df) * 100
            )
      .round(2)
)

cancellation_by_service

In [ ]:
#Chart for Cancellation Rate by Shipping Service Level
cancellation_by_service.plot(kind='bar', figsize=(8,5), color='red')
plt.title("Cancellation Rate by Shipping Service Level (%)")
plt.xlabel("Shipping Service Level")
plt.ylabel("Cancellation Rate (%)")
plt.xticks(rotation=45)
plt.show()

In [ ]:
# Cancellation impact by Status
status_cancel = (
    df[df['Status'].str.lower().str.contains('|'.join(cancel_keywords), na=False)]
    .groupby('Status')['Order ID']
    .count()
    .sort_values(ascending=False)
)

status_cancel

In [ ]:
# Chart for Cancellation Impact by Status
status_cancel.plot(kind='bar', figsize=(10,5), color='red')
plt.title("Cancelled Orders by Status")
plt.xlabel("Order Status")
plt.ylabel("Number of Cancelled Orders")
plt.xticks(rotation=45)
plt.show()

## 3) Improving customer experience through better service policies

In [ ]:
#Delivered vs Cancelled Comparison
delivery_success = pd.crosstab(df['Status'], df['ship-service-level'])
delivery_success

# ***Rough Work***

---

## April Cancellation Rate

In [ ]:
# Ensure Date column is in datetime format
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Filter data for April
april_df = df[df['Date'].dt.month == 4]

# Total orders in April
total_orders_april = len(april_df)
print("Total Orders in April:", total_orders_april)

In [ ]:
# Cancelled orders in April
cancelled_orders_april = april_df['Status'].str.lower().str.contains(
    '|'.join(cancel_keywords),
    na=False
).sum()

print("Total Cancelled Orders in April:", cancelled_orders_april)

In [ ]:
# Cancellation rate (%)
april_cancellation_rate = (cancelled_orders_april / total_orders) * 100
print("April Cancellation Rate:", round(april_cancellation_rate, 2), "%")

## Quantity sold for M size

In [ ]:
m_size_set_qty = df[
    (df['Size'].str.upper() == 'M') &
    (df['Category'].str.lower() == 'set')
]['Qty'].sum()

print("Total quantity sold for M size in 'set' category:", m_size_set_qty)

## May Revenue

In [ ]:
# Total revenue for May
may_revenue = df[df['Date'].dt.month == 5]['Amount'].sum()
may_revenue

## City wise Sales

In [ ]:
city_sales = df.groupby('ship-city')['Amount'].sum().sort_values(ascending=False)
city_sales

In [ ]:
second_highest_city = city_sales.index[1]
second_highest_city

## June Revenue

In [ ]:
june_revenue = df[df['Date'].dt.month == 6]['Amount'].sum()
june_revenue

## Highest Day Sale

In [ ]:
df['Day_Name'] = df['Date'].dt.day_name()

In [ ]:
day_wise_sales = df.groupby('Day_Name')['Amount'].sum()
day_wise_sales

In [ ]:
day_sales = df.groupby('Day_Name')['Amount'].sum()

In [ ]:
highest_sales_day = day_sales.idxmax()
print("Day with highest sales:", highest_sales_day)

In [ ]:
df.to_csv("sales_dataset.csv", index=False)

In [ ]:
from google.colab import files
files.download("sales_dataset.csv")

# Conclusion & Recommendation

**Conclusion:**

Overall, the analysis shows that integrating operational efficiency, growth strategies, customer-centric practices, effective inventory management, and data-driven decision-making can significantly improve performance and ensure sustainable success in the competitive e-commerce market.

*   Total Revenue: The total revenue generated from the dataset is ₹7,17,72,313.62.

*  Peak Sales Period: April was the peak sales month, contributing the highest number of orders.

*  Average Order Value (AOV): Overall AOV is ₹556.62.

*  Cancellation Rate: Overall cancellation rate is 15.86%.

*  Weekly Trends: Orders are highest on [Sunday].



---


**Recommendations:**  

*  Operational Optimization: Improve logistics for high-cancellation shipping methods and couriers to reduce failed deliveries.

*  Revenue & Growth Strategy: Focus on peak months like April for targeted promotions, offers, and marketing campaigns.

*  Customer-Centric Improvements: Address high-cancellation categories and improve customer communication to reduce cancellations.

*  Inventory & Product Management: Optimize stock for high-demand categories and plan inventory around peak months to avoid stockouts.

*  Data-Driven Decision Making: Continuously monitor AOV, average quantity per order, and cancellation rates to identify trends and optimize strategies.